In [1]:
import pandas as pd
import numpy as np
import random

In [2]:
img_lst = pd.read_csv("test/test_list.csv")
img_lst = [ str(i[0]) for i in img_lst.values ]

In [3]:
idty = []
for i in img_lst:
    idty.append(i.split("/"))

In [4]:
df = pd.DataFrame(idty)

In [5]:
c = df[0].values

In [6]:
classes = list(df[0].unique())
classes = list(df[0].unique())
min_classes = min(df[0].value_counts())
mapping = {}
for i in classes:
    mapping[i] = np.where(c == i)

In [54]:
ran_pos = random.choices(mapping[classes[0]][0], k = 50)
ran_neg = random.choices(np.vstack([mapping[i][0].reshape(-1,1).T for i in classes if(i != classes[0])]), k = 50)

In [11]:
len(mapping)

500

In [56]:
len(ran_neg)

50

In [57]:
ran_neg

[array([   424,    425,    426, ..., 169393, 169394, 169395], dtype=int64),
 array([   424,    425,    426, ..., 169393, 169394, 169395], dtype=int64),
 array([   424,    425,    426, ..., 169393, 169394, 169395], dtype=int64),
 array([   424,    425,    426, ..., 169393, 169394, 169395], dtype=int64),
 array([   424,    425,    426, ..., 169393, 169394, 169395], dtype=int64),
 array([   424,    425,    426, ..., 169393, 169394, 169395], dtype=int64),
 array([   424,    425,    426, ..., 169393, 169394, 169395], dtype=int64),
 array([   424,    425,    426, ..., 169393, 169394, 169395], dtype=int64),
 array([   424,    425,    426, ..., 169393, 169394, 169395], dtype=int64),
 array([   424,    425,    426, ..., 169393, 169394, 169395], dtype=int64),
 array([   424,    425,    426, ..., 169393, 169394, 169395], dtype=int64),
 array([   424,    425,    426, ..., 169393, 169394, 169395], dtype=int64),
 array([   424,    425,    426, ..., 169393, 169394, 169395], dtype=int64),
 array([   4

In [34]:
mapping[classes[0]][0].reshape(-1,1).shape

(424, 1)

In [36]:
mapping[classes[1]][0].reshape(-1,1).shape

(136, 1)

In [58]:
np.hstack([mapping[classes[0]][0].T, mapping[classes[6]][0].T ]).shape

(703,)

In [14]:
img_lst

['n000001/0001_01.jpg',
 'n000001/0002_01.jpg',
 'n000001/0003_01.jpg',
 'n000001/0004_01.jpg',
 'n000001/0005_01.jpg',
 'n000001/0006_01.jpg',
 'n000001/0007_01.jpg',
 'n000001/0008_01.jpg',
 'n000001/0009_01.jpg',
 'n000001/0010_01.jpg',
 'n000001/0011_01.jpg',
 'n000001/0012_01.jpg',
 'n000001/0013_01.jpg',
 'n000001/0014_01.jpg',
 'n000001/0015_01.jpg',
 'n000001/0016_01.jpg',
 'n000001/0017_01.jpg',
 'n000001/0018_01.jpg',
 'n000001/0019_01.jpg',
 'n000001/0020_01.jpg',
 'n000001/0021_01.jpg',
 'n000001/0022_01.jpg',
 'n000001/0023_01.jpg',
 'n000001/0024_01.jpg',
 'n000001/0025_01.jpg',
 'n000001/0026_02.jpg',
 'n000001/0027_03.jpg',
 'n000001/0028_01.jpg',
 'n000001/0029_01.jpg',
 'n000001/0030_01.jpg',
 'n000001/0031_01.jpg',
 'n000001/0032_01.jpg',
 'n000001/0033_01.jpg',
 'n000001/0034_02.jpg',
 'n000001/0035_01.jpg',
 'n000001/0036_01.jpg',
 'n000001/0037_01.jpg',
 'n000001/0038_01.jpg',
 'n000001/0039_01.jpg',
 'n000001/0040_01.jpg',
 'n000001/0041_01.jpg',
 'n000001/0042_0

In [26]:
[  i for i in range(20) if(i != 2)]

[0, 1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [51]:
s = [mapping[i][0].reshape(-1,1).T for i in classes if(i != classes[0])]

In [52]:
for i in s:
    print(i.shape)

(1, 136)
(1, 454)
(1, 180)
(1, 458)
(1, 441)
(1, 279)
(1, 585)
(1, 367)
(1, 522)
(1, 208)
(1, 431)
(1, 344)
(1, 505)
(1, 242)
(1, 199)
(1, 454)
(1, 312)
(1, 329)
(1, 357)
(1, 446)
(1, 200)
(1, 440)
(1, 491)
(1, 526)
(1, 400)
(1, 301)
(1, 444)
(1, 210)
(1, 324)
(1, 310)
(1, 261)
(1, 580)
(1, 186)
(1, 306)
(1, 477)
(1, 410)
(1, 259)
(1, 353)
(1, 257)
(1, 451)
(1, 229)
(1, 219)
(1, 236)
(1, 159)
(1, 308)
(1, 594)
(1, 203)
(1, 302)
(1, 231)
(1, 544)
(1, 182)
(1, 423)
(1, 379)
(1, 644)
(1, 430)
(1, 243)
(1, 502)
(1, 305)
(1, 303)
(1, 237)
(1, 324)
(1, 320)
(1, 268)
(1, 206)
(1, 267)
(1, 573)
(1, 369)
(1, 452)
(1, 402)
(1, 395)
(1, 217)
(1, 438)
(1, 204)
(1, 204)
(1, 321)
(1, 275)
(1, 294)
(1, 328)
(1, 481)
(1, 225)
(1, 456)
(1, 240)
(1, 230)
(1, 275)
(1, 538)
(1, 373)
(1, 281)
(1, 99)
(1, 281)
(1, 638)
(1, 225)
(1, 167)
(1, 212)
(1, 253)
(1, 416)
(1, 440)
(1, 150)
(1, 397)
(1, 305)
(1, 278)
(1, 313)
(1, 470)
(1, 383)
(1, 266)
(1, 345)
(1, 327)
(1, 158)
(1, 319)
(1, 336)
(1, 248)
(1, 213)
(1